# Generated by Django 2.1.4 on 2018-12-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winter_web', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
